name: maket
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audio_wave: ^0.1.2
  getwidget: ^2.0.5
  syncfusion_flutter_sliders: ^19.4.53
  syncfusion_flutter_core: ^19.4.53

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/icons/


